---
title: "Helpers for working with matrices"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Helpers for working with matrices}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = 'center', 
  fig.dim = c(7, 7), 
  out.width = "50%"
)
#devtools::load_all() # TODO
library("oeli")
```

## Check correlation matrix

Is a given object a correlation matrix? This can be checked in three ways as follows:

```{r, check_correlation_matrix, error = TRUE}
### N is a correlation matrix
N <- diag(3)
check_correlation_matrix(N, dim = 3)
test_correlation_matrix(N, dim = 3)
assert_correlation_matrix(N, dim = 3)

### M is not a correlation matrix
M <- matrix(c(1,  0.9,  0.9, 0.9,  1,  -0.9, 0.9,  -0.9,  1), nrow = 3)
check_correlation_matrix(M)
test_correlation_matrix(M)
assert_correlation_matrix(M)
```

## Check covariance matrix

The same checks for a correlation matrix also work for a covariance matrix:

```{r, check_covariance_matrix, error = TRUE}
### N is a covariance matrix
N <- diag(3)
check_covariance_matrix(N, dim = 3)
test_covariance_matrix(N, dim = 3)
assert_covariance_matrix(N, dim = 3)

### M is not a correlation matrix
M <- matrix(c(1, 2, 3, 2, 1, 2, 3, 2, 1), nrow = 3)
check_covariance_matrix(M)
test_covariance_matrix(M)
assert_covariance_matrix(M)
```

## Check transistion probability matrix

And what about transition probability matrices?

```{r, check_transition_probability_matrix, error = TRUE}
### T1 is a transition probability matrix
T1 <- matrix(c(0.8,  0.2,  0, 0.1,  0.7,  0.4, 0.1,  0.1,  0.6), nrow = 3)
check_transition_probability_matrix(T1)
test_transition_probability_matrix(T1)
assert_transition_probability_matrix(T1)

### T2 is not a transition probability matrix
T2 <- matrix(c(0.8,  0.2,  0.1, 0.1,  0.7,  0.4, 0.1,  0.1,  0.6), nrow = 3)
check_transition_probability_matrix(T2)
test_transition_probability_matrix(T2)
assert_transition_probability_matrix(T2)
```
## Cholesky root of covariance matrix

```{r, cholesky_root}
(cov <- sample_covariance_matrix(4))
(chol <- cov_to_chol(cov))
all.equal(cov, chol_to_cov(chol))
```
