---
title: "Helpers for working with vectors"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Helpers for working with vectors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = 'center', 
  fig.dim = c(7, 7), 
  out.width = "50%"
)
#devtools::load_all() # TODO
library("oeli")
```

## Check numeric vector

Is a given object a numeric vector? This can be checked in three ways as follows:

```{r, check_numeric_vector, error = TRUE}
### x is a numeric vector
x <- 1:3
check_numeric_vector(x)
test_numeric_vector(x)
assert_numeric_vector(x)

### y is not a numeric vector
y <- c(1, 2, "3")
check_numeric_vector(y)
test_numeric_vector(y)
assert_numeric_vector(y)
```

## Check probability vector

A probability vector is a special type of numeric vector:

```{r, check_probability_vector, error = TRUE}
### p1 is a probability vector
p1 <- c(0.2, 0.3, 0.5)
check_probability_vector(p1)
test_probability_vector(p1)
assert_probability_vector(p1)

### p2 is not a probability vector
p2 <- c(0.2, 0.3, 0.6)
check_probability_vector(p2)
test_probability_vector(p2)
assert_probability_vector(p2)
```

## Split a vector into chunks

```{r, chunk_vector}
x <- 1:12
chunk_vector(x, n = 3, type = 1)
chunk_vector(x, n = 3, type = 2)
try(chunk_vector(x, n = 5, strict = TRUE))
```

## Generate vector subsets

The `subsets()` function generates subsets of a vector.

```{r, subsets}
v <- month.name[1:3]

### all subsets
subsets(v)

### only subsets of length 1 or 3
subsets(v, c(1, 3)) 

### the trivial case also works
subsets(integer())  
```
